package com.example.wso2;

import com.example.wso2.utils.MockPassUtils;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.crypto.ECDHDecrypter;
import com.nimbusds.jwt.EncryptedJWT;
import com.nimbusds.jwt.SignedJWT;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.oltu.oauth2.client.request.OAuthClientRequest;
import org.apache.oltu.oauth2.client.response.OAuthAuthzResponse;
import org.apache.oltu.oauth2.client.response.OAuthClientResponse;
import org.apache.oltu.oauth2.common.exception.OAuthSystemException;
import org.apache.oltu.oauth2.common.message.types.GrantType;
import org.json.JSONException;
import org.json.JSONObject;
import org.wso2.carbon.identity.application.authentication.framework.context.AuthenticationContext;
import org.wso2.carbon.identity.application.authentication.framework.exception.AuthenticationFailedException;
import org.wso2.carbon.identity.application.authenticator.oidc.OIDCAuthenticatorConstants;
import org.wso2.carbon.identity.application.authenticator.oidc.OpenIDConnectAuthenticator;
import org.wso2.carbon.identity.application.common.model.Property;
import org.wso2.carbon.identity.application.common.util.IdentityApplicationConstants;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.KeyPair;
import java.security.interfaces.ECPrivateKey;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * Custom WSO2 OIDC authenticator implementing a FAPI-compliant Singpass v3 authentication flow.
 *
 * <p>This authenticator extends {@link OpenIDConnectAuthenticator} and overrides key methods
 * to support the following security features required by Singpass:
 *
 * <ul>
 *   <li><b>PAR</b>  – Pushed Authorization Requests: authorization parameters are sent via a
 *       secure backchannel POST to the PAR endpoint before redirecting the browser.</li>
 *   <li><b>PKCE</b> – Proof Key for Code Exchange (S256): prevents authorization code
 *       interception attacks.</li>
 *   <li><b>DPoP</b> – Demonstrating Proof of Possession: binds access tokens to an ephemeral
 *       EC key pair generated per session.</li>
 *   <li><b>Private-key JWT</b> – Client authentication uses a signed JWT instead of a
 *       shared client secret.</li>
 *   <li><b>JWE</b>  – The ID token returned by Singpass is encrypted (ECDH-ES). This
 *       authenticator decrypts it before WSO2 attempts to parse it.</li>
 * </ul>
 *
 * <p><b>State format:</b> {@code sessionDataKey.SINGPASSV3}
 * <ul>
 *   <li>{@code sessionDataKey} – WSO2 session identifier used for session lookup on callback,
 *       also serves as the CSRF token (cryptographically random UUID generated by WSO2
 *       per session).</li>
 *   <li>{@code .SINGPASSV3} – suffix used by {@link #canHandle} to identify this as a Singpass
 *       callback.</li>
 *   <li>The {@code .} delimiter is used instead of WSO2's default {@code ,} because Singpass
 *       only allows {@code [A-Za-z0-9/+_-=.]+} in the state parameter.</li>
 * </ul>
 *
 * <p>All constants are defined in {@link MockPassConstants}.
 * Cryptographic and encoding helpers live in {@link MockPassUtils}.
 */
public class MockPassOIDCAuthenticator extends OpenIDConnectAuthenticator {

    private static final Log LOG = LogFactory.getLog(MockPassOIDCAuthenticator.class);

    /**
     * EC private key used to sign client assertion JWTs sent to the token endpoint.
     * Loaded lazily from the signing keystore on first use; volatile for thread safety.
     */
    private volatile ECPrivateKey signingKey;

    /**
     * EC private key used to decrypt the JWE-wrapped ID token returned by Singpass.
     * Loaded lazily from the encryption keystore on first use; volatile for thread safety.
     */
    private volatile ECPrivateKey encryptionKey;

    // ── Identity ──────────────────────────────────────────────────────────────

    /**
     * Returns the unique internal name of this authenticator.
     * Used by WSO2 to identify and load the authenticator from the OSGi registry.
     *
     * @return the authenticator name defined in {@link MockPassConstants#AUTHENTICATOR_NAME}.
     */
    @Override
    public String getName() {
        return MockPassConstants.AUTHENTICATOR_NAME;
    }

    /**
     * Returns the human-readable display name shown in the WSO2 management console.
     *
     * @return the friendly name defined in {@link MockPassConstants#AUTHENTICATOR_FRIENDLY_NAME}.
     */
    @Override
    public String getFriendlyName() {
        return MockPassConstants.AUTHENTICATOR_FRIENDLY_NAME;
    }

    // ── Configuration properties ──────────────────────────────────────────────

    /**
     * Returns the list of configuration properties shown in the WSO2 management console
     * for this authenticator connection.
     *
     * <p>Inherits all standard OIDC properties from the parent class, then:
     * <ul>
     *   <li>Removes the {@code ClientSecret} field — Singpass uses private_key_jwt
     *       authentication, so no shared secret is needed.</li>
     *   <li>Adds a {@code par_endpoint} field for the Pushed Authorization Request URL.</li>
     * </ul>
     *
     * @return a {@link List} of {@link Property} objects defining the authenticator's UI fields.
     */
    @Override
    public List<Property> getConfigurationProperties() {
        List<Property> properties = new ArrayList<>(
                Optional.ofNullable(super.getConfigurationProperties())
                        .orElse(Collections.emptyList())
        );

        properties.removeIf(p ->
                IdentityApplicationConstants.Authenticator.OIDC.CLIENT_SECRET.equals(p.getName()));

        Property par = new Property();
        par.setName(MockPassConstants.PARAM_PAR_ENDPOINT);
        par.setDisplayName(MockPassConstants.PAR_ENDPOINT_DISPLAY_NAME);
        par.setRequired(true);
        par.setDescription(MockPassConstants.PAR_ENDPOINT_DESCRIPTION);
        properties.add(par);

        return properties;
    }

    // ── Session lookup ────────────────────────────────────────────────────────

    /**
     * Extracts the WSO2 {@code sessionDataKey} from the {@code state} parameter on the
     * callback request, enabling WSO2's {@code DefaultRequestCoordinator} to locate the
     * correct authentication session.
     *
     * <p><b>Why this override is needed:</b> The parent's default implementation expects
     * state in the format {@code sessionDataKey,OIDC} and splits on {@code ,} to extract
     * the {@code sessionDataKey}:
     * <pre>
     *     state.split(",")[0]  →  sessionDataKey
     * </pre>
     * However, Singpass strictly validates the {@code state} parameter against the pattern
     * {@code [A-Za-z0-9/+_-=.]+} — the {@code ,} character is not allowed, causing the
     * PAR request to be rejected with HTTP 400.
     *
     * <p><b>Solution:</b> We use {@code .} as the delimiter instead — it is valid per the
     * Singpass spec. The state format becomes:
     * <pre>
     *     sessionDataKey.SINGPASSV3
     * </pre>
     * This override splits on {@code .} and extracts the first part ({@code sessionDataKey}),
     * mirroring exactly what the parent does with {@code ,}.
     *
     * @param request the callback {@link HttpServletRequest} containing the {@code state}
     *                parameter echoed back by Singpass.
     * @return the {@code sessionDataKey} extracted from the first part of {@code state}
     *         (before the {@code .}), or the parent's result if state has no {@code .}.
     */
    @Override
    public String getContextIdentifier(HttpServletRequest request) {
        String state = request.getParameter(MockPassConstants.PARAM_STATE);
        if (state != null && state.contains(MockPassConstants.STATE_DELIMITER)) {
            return state.split(MockPassConstants.STATE_DELIMITER_REGEX)[0];
        }
        return super.getContextIdentifier(request);
    }

    // ── Callback detection ────────────────────────────────────────────────────
    /**
     * Determines whether this authenticator should handle the incoming request.
     *
     * <p><b>Why this override is needed:</b> The parent's default implementation checks
     * whether {@code getLoginType(request)} returns {@code "OIDC"} by splitting state on
     * {@code ,}:
     * <pre>
     *     state.split(",")[1].equals("OIDC")
     * </pre>
     * However, Singpass rejects {@code ,} in state (allowed pattern:
     * {@code [A-Za-z0-9/+_-=.]+}), so our state format uses {@code .} as delimiter:
     * <pre>
     *     sessionDataKey.SINGPASSV3
     * </pre>
     * Since the parent's {@code getLoginType} splits on {@code ,} and finds nothing,
     * it returns {@code null} — causing {@code canHandle} to always return {@code false}
     * on Singpass callbacks. This override corrects that by checking for {@code .SINGPASSV3}
     * suffix instead.
     *
     *
     * <p>The fallback to {@code super.canHandle(request)} preserves standard OIDC behaviour
     * for any other requests such as logout flows.
     *
     * @param request the incoming {@link HttpServletRequest}.
     * @return {@code true} if this authenticator should process the request; {@code false} otherwise.
     */
    @Override
    public boolean canHandle(HttpServletRequest request) {
        String code  = request.getParameter(MockPassConstants.PARAM_CODE);
        String state = request.getParameter(MockPassConstants.PARAM_STATE);

        boolean isMockPassCallback = code != null
                && state != null
                && state.endsWith(MockPassConstants.STATE_SINGPASSV3_SUFFIX);
        boolean handled = isMockPassCallback || super.canHandle(request);

        if (LOG.isDebugEnabled()) {
            LOG.debug("[MockPass] canHandle=" + handled + " code=" + (code != null));
        }
        return handled;
    }

    // ── PAR flow initiation ───────────────────────────────────────────────────

    /**
     * Initiates the Singpass FAPI authentication flow using Pushed Authorization Requests (PAR).
     *
     * <p><b>Execution order:</b>
     * <ol>
     *   <li>Generates a fresh ephemeral EC key pair for DPoP binding (one per session).</li>
     *   <li>Builds the {@code state} value in the format {@code sessionDataKey.SINGPASSV3} where
     *       {@code sessionDataKey} is the WSO2 session identifier used for session lookup on
     *       callback, and {@code .SINGPASSV3} is the suffix used by {@link #canHandle} to identify
     *       this as a Singpass callback. The {@code .} delimiter is used instead of the
     *       parent's default {@code ,} because Singpass only allows
     *       {@code [A-Za-z0-9/+_-=.]+} in the state parameter.</li>
     *   <li>Generates a random {@code nonce} for replay protection.</li>
     *   <li>Generates a PKCE code verifier and its S256 challenge.</li>
     *   <li>Builds a DPoP proof JWT bound to the PAR endpoint and POST method.</li>
     *   <li>Builds a private_key_jwt client assertion for client authentication.</li>
     *   <li>POSTs all authorization parameters to the PAR endpoint (backchannel).</li>
     *   <li>Redirects the browser to the authorization endpoint with only
     *       {@code client_id} and the {@code request_uri} returned by the PAR endpoint.</li>
     * </ol>
     *
     * @param request  the incoming {@link HttpServletRequest} from the browser.
     * @param response the {@link HttpServletResponse} used to issue the browser redirect.
     * @param context  the {@link AuthenticationContext} carrying per-session properties.
     * @throws AuthenticationFailedException wrapping:
     *         <ul>
     *           <li>{@link GeneralSecurityException} – EC key pair generation or keystore
     *               access failed.</li>
     *           <li>{@link JOSEException} – DPoP JWT or client assertion signing failed.</li>
     *           <li>{@link IOException} – PAR HTTP request or browser redirect failed.</li>
     *         </ul>
     */
    @Override
    protected void initiateAuthenticationRequest(HttpServletRequest request,
                                                 HttpServletResponse response,
                                                 AuthenticationContext context)
            throws AuthenticationFailedException {

        if (LOG.isDebugEnabled()) {
            LOG.debug("[MockPass] initiateAuthenticationRequest invoked");
        }

        try {
            Map<String, String> props = context.getAuthenticatorProperties();

            String clientId      = props.get(OIDCAuthenticatorConstants.CLIENT_ID);
            String parEndpoint   = props.get(MockPassConstants.PARAM_PAR_ENDPOINT);
            String authEndpoint  = props.get(OIDCAuthenticatorConstants.OAUTH2_AUTHZ_URL);
            String tokenEndpoint = props.get(OIDCAuthenticatorConstants.OAUTH2_TOKEN_URL);
            String callback      = getCallbackUrl(props, context);

            KeyPair ephemeralKeyPair = MockPassUtils.generateEphemeralKeyPair();
            context.setProperty(MockPassConstants.CTX_EPHEMERAL_KEY, ephemeralKeyPair);

            String nonce      = UUID.randomUUID().toString();
            context.setProperty(getName() + MockPassConstants.OIDC_FEDERATION_NONCE, nonce);
            String stateValue = context.getContextIdentifier() + MockPassConstants.STATE_SINGPASSV3_SUFFIX;

            context.setProperty(MockPassConstants.CTX_STATE, context.getContextIdentifier());

            String codeVerifier  = MockPassUtils.generateCodeVerifier();
            String codeChallenge = MockPassUtils.computeCodeChallenge(codeVerifier);
            context.setProperty(MockPassConstants.CTX_CODE_VERIFIER, codeVerifier);

            String keyAlias = getAuthenticatorConfig().getParameterMap()
                    .get(MockPassConstants.PARAM_KEY_ALIAS);
            String dpop = MockPassUtils.generateDPoP(
                    parEndpoint, MockPassConstants.HTTP_METHOD_POST, ephemeralKeyPair);
            String clientAssertion = MockPassUtils.generateClientAssertionJwt(
                    clientId, tokenEndpoint, keyAlias, getSigningKey());

            String requestUri = pushAuthorizationRequest(
                    parEndpoint, clientId, callback, stateValue, nonce,
                    codeChallenge, clientAssertion, dpop);

            String authUrl = authEndpoint
                    + "?" + MockPassConstants.PARAM_KEY_CLIENT_ID
                    + "=" + MockPassUtils.encode(clientId)
                    + "&" + MockPassConstants.PARAM_KEY_REQUEST_URI
                    + "=" + MockPassUtils.encode(requestUri);

            if (LOG.isDebugEnabled()) {
                LOG.debug("[MockPass] Redirecting to authorization endpoint: " + authEndpoint);
            }
            response.sendRedirect(authUrl);

        } catch (GeneralSecurityException e) {
            throw new AuthenticationFailedException(
                    "EC key generation or keystore access failed during MockPass PAR initiation", e);
        } catch (JOSEException e) {
            throw new AuthenticationFailedException(
                    "JWT signing failed during MockPass PAR initiation", e);
        } catch (IOException e) {
            throw new AuthenticationFailedException(
                    "Network I/O error during MockPass PAR request or browser redirect", e);
        }
    }

    // ── Callback processing ───────────────────────────────────────────────────

    /**
     * Validates the {@code state} parameter returned by Singpass to prevent CSRF attacks,
     * then delegates to the parent class to complete the token exchange.
     *
     * <p><b>State validation logic:</b>
     * The state returned by Singpass has the format {@code sessionDataKey.SINGPASSV3}.
     * Only the {@code sessionDataKey} prefix (before the {@code .}) is compared against
     * the value stored in context during {@link #initiateAuthenticationRequest}
     *
     * <p>The {@code sessionDataKey} is a cryptographically random UUID generated by WSO2
     * per session — it serves as both the session identifier and the CSRF token, following
     * the same design as the parent class which uses {@code sessionDataKey} in the same role.
     *
     * <p>If the {@code sessionDataKey} portions do not match, the flow is aborted immediately
     * with a CSRF warning and the parent's token exchange is never called.
     *
     * @param request  the callback {@link HttpServletRequest} containing {@code code} and
     *                 {@code state} parameters echoed back from Singpass.
     * @param response the {@link HttpServletResponse}.
     * @param context  the {@link AuthenticationContext} holding the original {@code sessionDataKey}
     *                 stored during {@link #initiateAuthenticationRequest}.
     * @throws AuthenticationFailedException if:
     *         <ul>
     *           <li>The returned {@code sessionDataKey} does not match the stored one
     *               (possible CSRF attack).</li>
     *           <li>The parent's token exchange or claim processing fails.</li>
     *         </ul>
     */
    @Override
    protected void processAuthenticationResponse(HttpServletRequest request,
                                                 HttpServletResponse response,
                                                 AuthenticationContext context)
            throws AuthenticationFailedException {

        String returnedState = request.getParameter(MockPassConstants.PARAM_STATE);
        String originalState = (String) context.getProperty(MockPassConstants.CTX_STATE);

        if (originalState != null && returnedState != null) {
            String returnedSessionDataKey = returnedState.contains(MockPassConstants.STATE_DELIMITER)
                    ? returnedState.split(MockPassConstants.STATE_DELIMITER_REGEX)[0]
                    : returnedState;

            if (!originalState.equals(returnedSessionDataKey)) {
                throw new AuthenticationFailedException(
                        "State mismatch – possible CSRF attack. " +
                                "expected=" + originalState + " received=" + returnedSessionDataKey);
            }
        }

        super.processAuthenticationResponse(request, response, context);
    }

    // ── Token request construction ────────────────────────────────────────────

    /**
     * Builds the HTTP token request sent to the Singpass token endpoint.
     *
     * <p>Unlike the standard OIDC flow (client_id + client_secret), Singpass requires:
     * <ul>
     *   <li><b>private_key_jwt</b> – a signed JWT for client authentication (no shared secret).
     *       Parameters: {@code client_assertion_type} and {@code client_assertion}.</li>
     *   <li><b>PKCE code_verifier</b> – proves this request originates from the same party
     *       that sent the PAR request.</li>
     *   <li><b>DPoP header</b> – a proof-of-possession JWT bound to the ephemeral EC key pair
     *       generated at session start, binding the issued token to this specific client.</li>
     * </ul>
     *
     * @param context       the {@link AuthenticationContext} containing:
     *                      <ul>
     *                        <li>{@code CTX_CODE_VERIFIER} – the PKCE plain-text verifier.</li>
     *                        <li>{@code CTX_EPHEMERAL_KEY} – the session's ephemeral EC key pair
     *                            used to generate the DPoP proof.</li>
     *                      </ul>
     * @param authzResponse the {@link OAuthAuthzResponse} carrying the authorization code
     *                      returned by Singpass in the callback URL.
     * @return an {@link OAuthClientRequest} with all required parameters set in the POST body
     *         and a {@code DPoP} proof JWT attached as a request header.
     * @throws AuthenticationFailedException wrapping:
     *         <ul>
     *           <li>{@link OAuthSystemException} – the OAuthClientRequest builder failed to
     *               construct the request body.</li>
     *           <li>{@link GeneralSecurityException} – signing keystore could not be loaded
     *               or the key alias was not found.</li>
     *           <li>{@link JOSEException} – DPoP JWT or client assertion JWT signing failed.</li>
     *           <li>{@link IOException} – keystore file could not be read from disk.</li>
     *         </ul>
     */
    @Override
    protected OAuthClientRequest getAccessTokenRequest(AuthenticationContext context,
                                                       OAuthAuthzResponse authzResponse)
            throws AuthenticationFailedException {

        try {
            Map<String, String> props = context.getAuthenticatorProperties();

            String clientId      = props.get(OIDCAuthenticatorConstants.CLIENT_ID);
            String tokenEndpoint = props.get(OIDCAuthenticatorConstants.OAUTH2_TOKEN_URL);
            String callback      = getCallbackUrl(props, context);
            String codeVerifier  = (String) context.getProperty(MockPassConstants.CTX_CODE_VERIFIER);
            KeyPair keyPair      = (KeyPair) context.getProperty(MockPassConstants.CTX_EPHEMERAL_KEY);

            String keyAlias = getAuthenticatorConfig().getParameterMap()
                    .get(MockPassConstants.PARAM_KEY_ALIAS);
            String clientAssertion = MockPassUtils.generateClientAssertionJwt(
                    clientId, tokenEndpoint, keyAlias, getSigningKey());
            String dpop = MockPassUtils.generateDPoP(
                    tokenEndpoint, MockPassConstants.HTTP_METHOD_POST, keyPair);

            OAuthClientRequest tokenRequest = OAuthClientRequest
                    .tokenLocation(tokenEndpoint)
                    .setGrantType(GrantType.AUTHORIZATION_CODE)
                    .setRedirectURI(callback)
                    .setCode(authzResponse.getCode())
                    .setClientId(clientId)
                    .setParameter(MockPassConstants.PARAM_KEY_CLIENT_ASSERTION_TYPE,
                            MockPassConstants.CLIENT_ASSERTION_TYPE)
                    .setParameter(MockPassConstants.PARAM_KEY_CLIENT_ASSERTION, clientAssertion)
                    .setParameter(MockPassConstants.PARAM_KEY_CODE_VERIFIER, codeVerifier)
                    .buildBodyMessage();

            tokenRequest.addHeader(MockPassConstants.HTTP_HEADER_DPOP, dpop);
            return tokenRequest;

        } catch (OAuthSystemException e) {
            throw new AuthenticationFailedException(
                    "Failed to construct token request body: OAuthSystemException — " +
                            "check token endpoint URL and grant type configuration", e);
        } catch (GeneralSecurityException e) {
            throw new AuthenticationFailedException(
                    "Failed to load signing key from keystore for client assertion JWT: " +
                            "check keystore path, password, and alias", e);
        } catch (JOSEException e) {
            throw new AuthenticationFailedException(
                    "JWT signing failed for DPoP or client assertion: " +
                            "verify the EC private key is valid and uses the correct curve", e);
        } catch (IOException e) {
            throw new AuthenticationFailedException(
                    "Failed to read signing keystore file: " +
                            "verify the keystore file exists and is readable", e);
        }
    }

    // ── Token response handling ───────────────────────────────────────────────

    /**
     * Intercepts the token response from Singpass to decrypt the JWE-wrapped {@code id_token}
     * before the parent class attempts to parse it as a plain signed JWT.
     *
     * <p><b>Why this override is needed:</b> Singpass returns the ID token as a JWE
     * (JSON Web Encryption) wrapping a signed JWT. The parent's
     * {@code processAuthenticationResponse} calls {@code getIdTokenClaims(idToken)} which
     * tries to parse the raw token as JSON — this fails with a {@link ParseException} on
     * an encrypted token. By decrypting here and storing the plain signed JWT in context,
     * {@link #mapIdToken} returns the decrypted form before the parent ever reads the
     * encrypted token from the response.
     *
     * @param request the callback {@link HttpServletRequest}.
     * @param context the {@link AuthenticationContext} where the decrypted id_token is stored
     *                under the key {@link OIDCAuthenticatorConstants#ID_TOKEN}.
     * @return the {@link OAuthClientResponse} from the parent's token exchange, unchanged.
     *         The encrypted token remains in the response; the decrypted one is in context.
     * @throws AuthenticationFailedException wrapping:
     *         <ul>
     *           <li>{@link ParseException} – the id_token string is not a valid compact JWE.</li>
     *           <li>{@link JOSEException} – ECDH-ES decryption failed (wrong key or corrupt
     *               ciphertext).</li>
     *           <li>{@link GeneralSecurityException} – encryption keystore could not be loaded
     *               or the key alias was not found.</li>
     *           <li>{@link IOException} – encryption keystore file could not be read.</li>
     *         </ul>
     */
    @Override
    protected OAuthClientResponse requestAccessToken(HttpServletRequest request,
                                                     AuthenticationContext context)
            throws AuthenticationFailedException {

        OAuthClientResponse tokenResponse = super.requestAccessToken(request, context);

        String idToken = tokenResponse.getParam(OIDCAuthenticatorConstants.ID_TOKEN);
        if (idToken != null) {
            try {
                String decryptedIdToken = decryptIdToken(idToken);
                context.setProperty(OIDCAuthenticatorConstants.ID_TOKEN, decryptedIdToken);
            } catch (ParseException e) {
                throw new AuthenticationFailedException(
                        "id_token decryption failed: token is not a valid JWE — " +
                                "Singpass may have returned a plain JWT or the token is malformed", e);
            } catch (JOSEException e) {
                throw new AuthenticationFailedException(
                        "id_token ECDH-ES decryption failed: verify the encryption private key " +
                                "matches the public key registered with Singpass", e);
            } catch (GeneralSecurityException e) {
                throw new AuthenticationFailedException(
                        "id_token decryption failed: could not load encryption key from keystore — " +
                                "check encryption keystore path, password, and alias configuration", e);
            } catch (IOException e) {
                throw new AuthenticationFailedException(
                        "id_token decryption failed: encryption keystore file is unreadable — " +
                                "verify the file exists and has correct permissions", e);
            }
        }

        return tokenResponse;
    }

    /**
     * Returns the pre-decrypted {@code id_token} stored in context, bypassing the parent's
     * attempt to read the still-encrypted token from the token response object.
     *
     * <p>Called by the parent's {@code processAuthenticationResponse} immediately after
     * {@link #requestAccessToken}. Since decryption already happened there and the plain
     * signed JWT was stored in context, this method returns it directly — preventing the
     * parent from trying to JSON-parse the encrypted token from the response object.
     *
     * @param context       the {@link AuthenticationContext} holding the decrypted token
     *                      under {@link OIDCAuthenticatorConstants#ID_TOKEN}.
     * @param request       the callback {@link HttpServletRequest}.
     * @param tokenResponse the raw {@link OAuthClientResponse} from the token endpoint
     *                      (contains the encrypted token — not used here directly).
     * @return the decrypted signed JWT string if present in context; otherwise falls back
     *         to the parent's implementation which reads from the token response.
     * @throws AuthenticationFailedException if the parent fallback call fails.
     */
    @Override
    protected String mapIdToken(AuthenticationContext context,
                                HttpServletRequest request,
                                OAuthClientResponse tokenResponse)
            throws AuthenticationFailedException {

        String decrypted = (String) context.getProperty(OIDCAuthenticatorConstants.ID_TOKEN);
        return (decrypted != null) ? decrypted : super.mapIdToken(context, request, tokenResponse);
    }

    // ── PAR HTTP request ──────────────────────────────────────────────────────

    /**
     * Sends the Pushed Authorization Request (PAR) to the Singpass PAR endpoint via a
     * backchannel HTTP POST and returns the {@code request_uri} from the JSON response.
     *
     * <p>All authorization parameters (scope, state, nonce, PKCE, client assertion, DPoP)
     * are sent in the POST body — keeping them out of the browser URL bar. The server
     * responds with a short-lived {@code request_uri} used in the subsequent browser redirect.
     *
     * @param parEndpoint     the full URL of the PAR endpoint.
     * @param clientId        the OAuth client identifier registered with Singpass.
     * @param callback        the registered redirect URI where Singpass sends the callback.
     * @param state           the state value in format {@code sessionDataKey.SINGPASSV3} — the
     *                        {@code sessionDataKey} is the WSO2 session identifier and CSRF token,
     *                        {@code .SINGPASSV3} is the callback identification suffix.
     * @param nonce           a cryptographically random nonce for replay protection.
     * @param codeChallenge   the S256 PKCE code challenge derived from the code verifier.
     * @param clientAssertion the signed private_key_jwt for client authentication.
     * @param dpop            the DPoP proof JWT bound to the PAR endpoint and POST method.
     * @return the {@code request_uri} (e.g., {@code urn:ietf:params:oauth:request_uri:...})
     *         returned by the PAR server, valid for a short time window.
     * @throws AuthenticationFailedException if:
     *         <ul>
     *           <li>The server returns HTTP 4xx/5xx (includes the response body in the message).
     *               </li>
     *           <li>The response JSON does not contain a {@code request_uri} field.</li>
     *         </ul>
     * @throws IOException if a network connection error or stream read error occurs.
     */
    private String pushAuthorizationRequest(String parEndpoint,
                                            String clientId,
                                            String callback,
                                            String state,
                                            String nonce,
                                            String codeChallenge,
                                            String clientAssertion,
                                            String dpop)
            throws AuthenticationFailedException, IOException {

        String body = MockPassConstants.PARAM_KEY_CLIENT_ID
                + "=" + MockPassUtils.encode(clientId)
                + "&" + MockPassConstants.PARAM_KEY_REDIRECT_URI
                + "=" + MockPassUtils.encode(callback)
                + "&" + MockPassConstants.PARAM_KEY_RESPONSE_TYPE
                + "=" + MockPassUtils.encode(MockPassConstants.RESPONSE_TYPE_CODE)
                + "&" + MockPassConstants.PARAM_KEY_SCOPE
                + "=" + MockPassUtils.encode(MockPassConstants.SCOPE_OPENID_UINFIN)
                + "&" + MockPassConstants.PARAM_STATE
                + "=" + MockPassUtils.encode(state)
                + "&" + MockPassConstants.PARAM_KEY_NONCE
                + "=" + MockPassUtils.encode(nonce)
                + "&" + MockPassConstants.PARAM_KEY_CODE_CHALLENGE
                + "=" + MockPassUtils.encode(codeChallenge)
                + "&" + MockPassConstants.PARAM_KEY_CODE_CHALLENGE_METHOD
                + "=" + MockPassUtils.encode(MockPassConstants.CODE_CHALLENGE_METHOD)
                + "&" + MockPassConstants.PARAM_KEY_CLIENT_ASSERTION_TYPE
                + "=" + MockPassUtils.encode(MockPassConstants.CLIENT_ASSERTION_TYPE)
                + "&" + MockPassConstants.PARAM_KEY_CLIENT_ASSERTION
                + "=" + MockPassUtils.encode(clientAssertion);

        byte[] bodyBytes = body.getBytes(StandardCharsets.UTF_8);

        HttpURLConnection conn = (HttpURLConnection) new URL(parEndpoint).openConnection();
        try {
            conn.setConnectTimeout(MockPassConstants.PAR_CONNECT_TIMEOUT_MS);
            conn.setReadTimeout(MockPassConstants.PAR_READ_TIMEOUT_MS);
            conn.setRequestMethod(MockPassConstants.HTTP_METHOD_POST);
            conn.setDoOutput(true);
            conn.setRequestProperty(MockPassConstants.HTTP_HEADER_CONTENT_TYPE,
                    MockPassConstants.CONTENT_TYPE_FORM);
            conn.setRequestProperty(MockPassConstants.HTTP_HEADER_CONTENT_LENGTH,
                    String.valueOf(bodyBytes.length));
            conn.setRequestProperty(MockPassConstants.HTTP_HEADER_DPOP, dpop);

            try (OutputStream os = conn.getOutputStream()) {
                os.write(bodyBytes);
            }

            int status          = conn.getResponseCode();
            String responseBody = readBody(conn, status);


            if (status >= 400) {
                throw new AuthenticationFailedException(
                        "Singpass PAR endpoint rejected the request with HTTP " + status +
                                ". Response: " + responseBody);
            }

            try {
                return new JSONObject(responseBody)
                        .getString(MockPassConstants.PARAM_KEY_REQUEST_URI);
            } catch (JSONException e) {
                throw new AuthenticationFailedException(
                        "PAR response did not contain a valid 'request_uri' field. " +
                                "Response body: " + responseBody, e);
            }

        } finally {
            conn.disconnect();
        }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Reads and returns the full response body from an open {@link HttpURLConnection}.
     *
     * <p>Uses the error stream for HTTP 4xx/5xx responses (where the normal input stream
     * may be null), and the regular input stream for 2xx responses.
     *
     * @param conn   the open {@link HttpURLConnection} after the request has been sent.
     * @param status the HTTP response status code used to choose the correct stream.
     * @return the full response body as a UTF-8 string, or an empty string if the
     *         stream is null (server sent no body).
     * @throws IOException if an I/O error occurs while reading the stream.
     */
    private String readBody(HttpURLConnection conn, int status) throws IOException {
        InputStream is = (status >= 400) ? conn.getErrorStream() : conn.getInputStream();
        if (is == null) return "";
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(is, StandardCharsets.UTF_8))) {
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = br.readLine()) != null) sb.append(line);
            return sb.toString();
        }
    }

    /**
     * Decrypts a JWE-wrapped ID token and returns the inner signed JWT as a compact string.
     *
     * <p>Singpass wraps the ID token as {@code JWE(SignedJWT)} using ECDH-ES key agreement
     * with the client's registered EC public key. This method:
     * <ol>
     *   <li>Parses the compact JWE string into an {@link EncryptedJWT}.</li>
     *   <li>Decrypts it using the local EC private key via {@link ECDHDecrypter}.</li>
     *   <li>Extracts the inner {@link SignedJWT} from the decrypted payload.</li>
     *   <li>Returns its compact serialization for standard JWT claim parsing by the parent.</li>
     * </ol>
     *
     * @param encryptedJwt the compact-serialized JWE string received from the token endpoint
     *                     (five Base64url parts separated by dots).
     * @return the compact-serialized inner {@link SignedJWT} string (three Base64url parts
     *         separated by dots), ready for standard JWT claim parsing.
     * @throws ParseException           if {@code encryptedJwt} is not a valid compact JWE.
     * @throws JOSEException            if ECDH-ES decryption fails.
     * @throws GeneralSecurityException if the encryption private key cannot be loaded.
     * @throws IOException              if the encryption keystore file cannot be read.
     * @throws IllegalStateException    if the decrypted payload is not a {@link SignedJWT}.
     */
    private String decryptIdToken(String encryptedJwt)
            throws ParseException, JOSEException, GeneralSecurityException, IOException {

        EncryptedJWT jwe = EncryptedJWT.parse(encryptedJwt);
        jwe.decrypt(new ECDHDecrypter(getEncryptionKey()));
        SignedJWT inner = jwe.getPayload().toSignedJWT();
        if (inner == null) {
            throw new IllegalStateException(
                    "Decrypted JWE payload is not a SignedJWT ; " +
                            "Singpass id_token structure may have changed");
        }
        return inner.serialize();
    }

    /**
     * Returns the EC private key used for signing client assertion JWTs, loading it from
     * the configured signing keystore on first access using double-checked locking.
     *
     * <p>The key is loaded once and cached for the lifetime of the authenticator instance.
     * Concurrent requests during the first load are serialised by {@code synchronized}.
     *
     * <p>Configuration parameters used:
     * <ul>
     *   <li>{@link MockPassConstants#PARAM_SIGNING_KEYSTORE} – path relative to carbon.home.</li>
     *   <li>{@link MockPassConstants#PARAM_KEYSTORE_PASSWORD} – keystore and key password.</li>
     *   <li>{@link MockPassConstants#PARAM_KEY_ALIAS} – alias of the EC key entry.</li>
     * </ul>
     *
     * @return the {@link ECPrivateKey} for signing client assertion JWTs.
     * @throws GeneralSecurityException if the keystore cannot be loaded, the alias is missing,
     *                                   or the key is not an EC private key.
     * @throws IOException              if the keystore file cannot be read from disk.
     */
    private ECPrivateKey getSigningKey() throws GeneralSecurityException, IOException {
        if (signingKey == null) {
            synchronized (this) {
                if (signingKey == null) {
                    Map<String, String> p = getAuthenticatorConfig().getParameterMap();
                    signingKey = MockPassUtils.loadPrivateKey(
                            p.get(MockPassConstants.PARAM_SIGNING_KEYSTORE),
                            p.get(MockPassConstants.PARAM_KEYSTORE_PASSWORD),
                            p.get(MockPassConstants.PARAM_KEY_ALIAS));
                }
            }
        }
        return signingKey;
    }

    /**
     * Returns the EC private key used for decrypting JWE ID tokens, loading it from
     * the configured encryption keystore on first access using double-checked locking.
     *
     * <p>The key is loaded once and cached for the lifetime of the authenticator instance.
     * Concurrent requests during the first load are serialised by {@code synchronized}.
     *
     * <p>Configuration parameters used:
     * <ul>
     *   <li>{@link MockPassConstants#PARAM_ENCRYPTION_KEYSTORE} – path relative to carbon.home.</li>
     *   <li>{@link MockPassConstants#PARAM_ENCRYPTION_KEYSTORE_PASS} – keystore and key password.</li>
     *   <li>{@link MockPassConstants#PARAM_ENCRYPTION_KEY_ALIAS} – alias of the EC key entry.</li>
     * </ul>
     *
     * @return the {@link ECPrivateKey} for decrypting JWE ID tokens.
     * @throws GeneralSecurityException if the keystore cannot be loaded, the alias is missing,
     *                                   or the key is not an EC private key.
     * @throws IOException              if the keystore file cannot be read from disk.
     */
    private ECPrivateKey getEncryptionKey() throws GeneralSecurityException, IOException {
        if (encryptionKey == null) {
            synchronized (this) {
                if (encryptionKey == null) {
                    Map<String, String> p = getAuthenticatorConfig().getParameterMap();
                    encryptionKey = MockPassUtils.loadPrivateKey(
                            p.get(MockPassConstants.PARAM_ENCRYPTION_KEYSTORE),
                            p.get(MockPassConstants.PARAM_ENCRYPTION_KEYSTORE_PASS),
                            p.get(MockPassConstants.PARAM_ENCRYPTION_KEY_ALIAS));
                }
            }
        }
        return encryptionKey;
    }
}